name: french connection
favicon: null
layout_spectrum: 0.3467999140266329
typography_spectrum: 0.884206194896251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.10246316157281399
  lightness: 0.5487120770849288
  saturation: 0.5343029987998307
  rhythmicContrast: 0.44901866489090025
purpose: []
